name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # 24.04 पर कई पैकेज नहीं मिलते

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools python3-wheel \
            libffi-dev libssl-dev autoconf automake \
            libtool pkg-config liblzma-dev zlib1g-dev \
            libgl1-mesa-dev libgles2-mesa-dev \
            libncurses5 libncursesw5

          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip -d latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;21.4.7075529"

      - name: Set environment variables
        run: |
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/android-sdk/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Verify SDK tools
        run: |
          which aidl || echo "❌ AIDL missing"
          which javac || echo "❌ Java missing"
          sdkmanager --list | head -20

      - name: Build APK with Buildozer
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-apk
          path: bin/*.apk
