name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-setuptools \
          build-essential git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev libsqlite3-dev libbz2-dev zlib1g-dev \
          libncurses5 libncursesw5-dev libreadline-dev liblzma-dev \
          libjpeg-dev libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev

        pip install --upgrade pip
        pip install buildozer Cython==0.29.36

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: class-notes-apk
        path: bin/*.apk
