name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            unzip zip git python3-pip \
            libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Setup Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/

          yes | cmdline-tools/latest/bin/sdkmanager --licenses

          yes | cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;34.0.0" \
            "ndk;21.4.7075529"

          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/android-sdk/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/ndk/21.4.7075529" >> $GITHUB_PATH

      - name: Debug PATH (Check for aidl)
        run: |
          echo "PATH=$PATH"
          which python3 || echo "python3 not found"
          which pip || echo "pip not found"
          which buildozer || echo "buildozer not found"
          which javac || echo "javac not found"
          which aidl || echo "aidl not found"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
